In [356]:
import pandas as pd
import numpy as np

In [357]:
test = pd.read_csv('_test.csv')
train = pd.read_csv('_train.csv')

In [358]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,f1_score,f1_score
from sklearn.preprocessing import OneHotEncoder

In [359]:
print(train.isnull().sum())
print(test.isnull().sum())

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64
PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64


In [360]:
train['Age']=train['Age'].fillna(train['Age'].mean())
test['Age']=test['Age'].fillna(test['Age'].mean())

In [361]:
train.dropna(subset='Embarked',axis=0,inplace=True) #drop rows where embarked is null
test.dropna(subset='Embarked',axis=0,inplace=True) #drop rows where embarked is null

In [362]:
train.drop(columns=['Name','PassengerId','Cabin','Ticket'],inplace=True)
display(train.head())
test.drop(columns=['Name','PassengerId','Cabin','Ticket'],inplace=True)
display(test.head())

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0       3    male  34.5      0      0   7.8292        Q
1       3  female  47.0      1      0   7.0000        S
2       2    male  62.0      0      0   9.6875        Q
3       3    male  27.0      0      0   8.6625        S
4       3  female  22.0      1      1  12.2875        S

In [363]:
test.dropna(subset='Fare',axis=0,inplace=True) #drop rows where fare is null

In [364]:
print(train.isnull().sum())
print(test.isnull().sum())

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64


In [365]:
# onehot encoding
train = pd.get_dummies(train, columns=['Sex','Embarked'])
test = pd.get_dummies(test, columns=['Sex','Embarked'])

In [366]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [367]:
train[['Fare']] = scaler.fit_transform(train[['Fare']])
train[['Age']] = scaler.fit_transform(train[['Age']])

test[['Age','Fare']] = scaler.fit_transform(test[['Age','Fare']])

In [368]:
train

Survived  Pclass       Age  SibSp  Parch      Fare  Sex_female  Sex_male  \
0           0       3 -0.590495      1      0 -0.500240           0         1   
1           1       1  0.643971      1      0  0.788947           1         0   
2           1       3 -0.281878      0      0 -0.486650           1         0   
3           1       1  0.412509      1      0  0.422861           1         0   
4           0       3  0.412509      0      0 -0.484133           0         1   
..        ...     ...       ...    ...    ...       ...         ...       ...   
886         0       2 -0.204724      0      0 -0.384475           0         1   
887         1       1 -0.821957      0      0 -0.042213           1         0   
888         0       3  0.003524      1      2 -0.174084           1         0   
889         1       1 -0.281878      0      0 -0.042213           0         1   
890         0       3  0.181046      0      0 -0.490173           0         1   

     Embarked_C  Embarked_Q  Embarked_S  
0             0           0           1  
1             1           0           0  
2             0           0           1  
3             0           0           1  
4             0           0           1  
..          ...         ...         ...  
886           0           0           1  
887           0           0           1  
888           0           0           1  
889           1           0           0  
890           0           1           0  

[889 rows x 11 columns]

In [369]:
test

Pclass       Age  SibSp  Parch      Fare  Sex_female  Sex_male  \
0         3  0.342695      0      0 -0.497811           0         1   
1         3  1.338924      1      0 -0.512660           1         0   
2         2  2.534399      0      0 -0.464532           0         1   
3         3 -0.255043      0      0 -0.482888           0         1   
4         3 -0.653535      1      1 -0.417971           1         0   
..      ...       ...    ...    ...       ...         ...       ...   
413       3  0.005777      0      0 -0.493856           0         1   
414       1  0.701337      0      0  1.312180           1         0   
415       3  0.661488      0      0 -0.508183           0         1   
416       3  0.005777      0      0 -0.493856           0         1   
417       3  0.005777      1      1 -0.237621           0         1   

     Embarked_C  Embarked_Q  Embarked_S  
0             0           1           0  
1             0           0           1  
2             0           1           0  
3             0           0           1  
4             0           0           1  
..          ...         ...         ...  
413           0           0           1  
414           1           0           0  
415           0           0           1  
416           0           0           1  
417           1           0           0  

[417 rows x 10 columns]

In [370]:
train_dup = train
train=train.iloc[:,1::]

y_train=train_dup.loc[:,"Survived"]

In [371]:
train_x,val_x,train_y,val_y=train_test_split(train,y_train,test_size=0.2,random_state=1)

In [372]:
train_x

Pclass       Age  SibSp  Parch      Fare  Sex_female  Sex_male  \
121       3  0.003524      0      0 -0.484133           0         1   
687       3 -0.821957      0      0 -0.441435           0         1   
790       3  0.003524      0      0 -0.490173           0         1   
837       3  0.003524      0      0 -0.484133           0         1   
659       1  2.187053      0      2  1.634368           0         1   
..      ...       ...    ...    ...       ...         ...       ...   
716       1  0.643971      0      0  3.934570           1         0   
768       3  0.003524      1      0 -0.159991           0         1   
73        3 -0.281878      1      0 -0.355197           0         1   
236       2  1.106896      1      0 -0.122745           0         1   
37        3 -0.667649      0      0 -0.484133           0         1   

     Embarked_C  Embarked_Q  Embarked_S  
121           0           0           1  
687           0           0           1  
790           0           1           0  
837           0           0           1  
659           1           0           0  
..          ...         ...         ...  
716           1           0           0  
768           0           1           0  
73            1           0           0  
236           0           0           1  
37            0           0           1  

[711 rows x 10 columns]

In [373]:
val_x

Pclass       Age  SibSp  Parch      Fare  Sex_female  Sex_male  \
387       2  0.489663      0      0 -0.384475           1         0   
259       2  1.569820      0      1 -0.122745           1         0   
771       3  1.415512      0      0 -0.488075           0         1   
208       3 -1.053420      0      0 -0.490173           1         0   
683       3 -1.207728      5      2  0.298036           0         1   
..      ...       ...    ...    ...       ...         ...       ...   
499       3 -0.436187      0      0 -0.489251           0         1   
731       3 -1.439190      0      0 -0.267955           0         1   
373       1 -0.590495      0      0  2.084509           0         1   
588       3 -0.590495      0      0 -0.484133           0         1   
234       2 -0.436187      0      0 -0.434807           0         1   

     Embarked_C  Embarked_Q  Embarked_S  
387           0           0           1  
259           0           0           1  
771           0           0           1  
208           0           1           0  
683           0           0           1  
..          ...         ...         ...  
499           0           0           1  
731           1           0           0  
373           1           0           0  
588           0           0           1  
234           0           0           1  

[178 rows x 10 columns]

In [374]:
train_y

121    0
687    0
790    0
837    0
659    0
      ..
716    1
768    0
73     0
236    0
37     0
Name: Survived, Length: 711, dtype: int64

In [375]:
val_y

387    1
259    1
771    0
208    1
683    0
      ..
499    0
731    0
373    0
588    0
234    0
Name: Survived, Length: 178, dtype: int64

In [376]:
logreg = LogisticRegression()

In [377]:
logreg.fit(train_x,train_y)

LogisticRegression()

In [378]:
y_pred = logreg.predict(val_x)

In [379]:
y_pred

array([1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0])

In [380]:
logreg.coef_

array([[-1.0753423 , -0.50416033, -0.27176416, -0.03019028,  0.03626489,
         1.21571791, -1.21577618,  0.21637239,  0.06954919, -0.28597986]])

In [381]:
logreg.intercept_

array([2.52275203])

In [382]:
acc = accuracy_score(val_y,y_pred)

In [383]:
acc

0.8426966292134831

In [384]:
confusion_matrix(val_y,y_pred)

array([[91, 14],
       [14, 59]])

In [385]:
print(precision_score(val_y,y_pred))
print(f1_score(val_y,y_pred))
print(recall_score(val_y,y_pred))

0.8082191780821918
0.8082191780821918
0.8082191780821918
